// AI Proactive Coach — generates a daily briefing aggregating signals from every module.
// Cached per (user, date). Re-generated by user action via "refresh" button.

import { getSupabaseAdmin, isSupabaseConfigured } from '@/lib/db/client'
import { getAIModel, isMockMode } from '@/lib/ai/provider'
import { generateText } from 'ai'
import { getPersonalisationContext } from '@/lib/personalisation/context'

export interface BriefingHighlight {
  label: string
  value: string
  link?: string
  emoji?: string
}

export interface BriefingPayload {
  date: string
  content_md: string
  highlights: BriefingHighlight[]
  generated_at: string
}

interface RawSignals {
  todayTasks: number
  overdueTasks: number
  doneTasks: number
  todayHabits: number
  doneHabits: number
  recentMood: number | null
  recentStress: number | null
  unreadNotifications: number
  urgentAuraAlerts: number
  birthdaysThisWeek: { name: string; date: string }[]
  followUpsThisWeek: { name: string }[]
  upcomingSIPs: { name: string; amount: number; date: string }[]
  upcomingMaintenance: { title: string; due: string }[]
  unpaidBills: number
  activeTrip: string | null
  journalDaysAgo: number | null
  topActiveGoal: string | null
  upcomingLegalDeadlines: { title: string; date: string }[]
  outstandingInvoiceCount: number
  outstandingInvoiceTotal: number
  todayMealsPlanned: number
}

async function gatherSignals(userId: string): Promise<RawSignals> {
  const db = getSupabaseAdmin()
  const today = new Date().toISOString().slice(0, 10)
  const weekAhead = new Date()
  weekAhead.setDate(weekAhead.getDate() + 7)
  const weekAheadStr = weekAhead.toISOString().slice(0, 10)

  const todayDow = new Date().getDay()

  const [
    tasks, doneTasksRow, habits, habitLogsToday, lastMood,
    notifs, profiles, contacts, sips, maint, bills, trips,
    lastJournal, goals, legalDeadlines, invoices, todayMeals,
  ] = await Promise.all([
    db.from('tasks').select('status, due_date').eq('user_id', userId).neq('status', 'done').neq('status', 'skipped'),
    db.from('tasks').select('id', { count: 'exact', head: true }).eq('user_id', userId).eq('status', 'done').gte('updated_at', new Date(Date.now() - 86_400_000).toISOString()),
    db.from('habits').select('id, days_of_week').eq('user_id', userId).eq('is_active', true),
    db.from('habit_logs').select('habit_id, count').eq('user_id', userId).eq('date', today),
    db.from('mood_logs').select('mood, stress, logged_at').eq('user_id', userId).order('logged_at', { ascending: false }).limit(1).maybeSingle(),
    db.from('notifications').select('id', { count: 'exact', head: true }).eq('user_id', userId).is('read_at', null),
    db.from('aura_profiles').select('data').eq('user_id', userId),
    db.from('contacts').select('name, birthday, follow_up_at').eq('user_id', userId).eq('archived', false),
    db.from('sip_plans').select('name, amount, next_date').eq('user_id', userId).eq('is_active', true).gte('next_date', today).lte('next_date', weekAheadStr).limit(5),
    db.from('home_maintenance').select('title, next_due_at').eq('user_id', userId).eq('is_active', true).gte('next_due_at', today).lte('next_due_at', weekAheadStr).limit(5),
    db.from('utility_bills').select('id', { count: 'exact', head: true }).eq('user_id', userId).eq('is_paid', false),
    db.from('trips').select('destination, start_date, end_date').eq('user_id', userId).in('status', ['active','booked']).order('start_date', { ascending: true }).limit(1).maybeSingle(),
    db.from('journal_entries').select('created_at').eq('user_id', userId).order('created_at', { ascending: false }).limit(1).maybeSingle(),
    db.from('career_goals').select('title').eq('user_id', userId).eq('status', 'active').order('updated_at', { ascending: false }).limit(1).maybeSingle(),
    db.from('legal_deadlines').select('title, due_date').eq('user_id', userId).eq('status', 'pending').gte('due_date', today).lte('due_date', weekAheadStr).order('due_date', { ascending: true }).limit(5),
    db.from('business_invoices').select('total').eq('user_id', userId).in('status', ['sent', 'overdue']),
    db.from('meal_plans').select('id', { count: 'exact', head: true }).eq('user_id', userId).eq('date', today),
  ])

  // Compute today's habits count
  const habitsArr = (habits.data ?? []) as { id: string; days_of_week: number[] }[]
  const todayHabitsList = habitsArr.filter(h => h.days_of_week.includes(todayDow))
  const logsToday = (habitLogsToday.data ?? []) as { habit_id: string; count: number }[]
  const doneHabitsCount = todayHabitsList.filter(h => {
    const log = logsToday.find(l => l.habit_id === h.id)
    return log && log.count > 0
  }).length

  // Birthdays this week (compare MM-DD)
  const todayMD = today.slice(5)
  const weekAheadMD = weekAheadStr.slice(5)
  const birthdaysThisWeek: { name: string; date: string }[] = []
  const followUpsThisWeek: { name: string }[] = []
  for (const c of (contacts.data ?? []) as { name: string; birthday: string | null; follow_up_at: string | null }[]) {
    if (c.birthday) {
      const md = c.birthday.slice(5)
      // Handle year-end wrap
      const inWindow = todayMD <= weekAheadMD
        ? md >= todayMD && md <= weekAheadMD
        : md >= todayMD || md <= weekAheadMD
      if (inWindow) birthdaysThisWeek.push({ name: c.name, date: c.birthday })
    }
    if (c.follow_up_at && c.follow_up_at >= today && c.follow_up_at <= weekAheadStr) {
      followUpsThisWeek.push({ name: c.name })
    }
  }

  // AURA urgent alerts (count from profiles — using calculateAlerts logic)
  let urgentCount = 0
  for (const p of (profiles.data ?? []) as { data: { milestone_records?: unknown[] } }[]) {
    // Lightweight check — do not import full aura-logic here to avoid coupling
    // Just count children with any milestone record marked 'concern'
    const records = p.data.milestone_records ?? []
    for (const r of records as { status?: string }[]) {
      if (r.status === 'concern') urgentCount++
    }
  }

  const allTasks = (tasks.data ?? []) as { status: string; due_date: string | null }[]
  const todayTasks = allTasks.filter(t => t.due_date === today).length
  const overdueTasks = allTasks.filter(t => t.due_date && t.due_date < today).length

  const invoiceRows = (invoices.data ?? []) as { total: number }[]
  const outstandingInvoiceTotal = invoiceRows.reduce((s, i) => s + Number(i.total ?? 0), 0)

  return {
    todayTasks, overdueTasks,
    doneTasks: doneTasksRow.count ?? 0,
    todayHabits: todayHabitsList.length,
    doneHabits: doneHabitsCount,
    recentMood: lastMood.data?.mood ?? null,
    recentStress: (lastMood.data as { stress?: number | null })?.stress ?? null,
    unreadNotifications: notifs.count ?? 0,
    urgentAuraAlerts: urgentCount,
    birthdaysThisWeek, followUpsThisWeek,
    upcomingSIPs: ((sips.data ?? []) as { name: string; amount: number; next_date: string }[]).map(s => ({ name: s.name, amount: s.amount, date: s.next_date })),
    upcomingMaintenance: ((maint.data ?? []) as { title: string; next_due_at: string }[]).map(m => ({ title: m.title, due: m.next_due_at })),
    unpaidBills: bills.count ?? 0,
    activeTrip: trips.data?.destination ?? null,
    journalDaysAgo: lastJournal.data ? Math.floor((Date.now() - new Date(lastJournal.data.created_at).getTime()) / 86_400_000) : null,
    topActiveGoal: goals.data?.title ?? null,
    upcomingLegalDeadlines: ((legalDeadlines.data ?? []) as { title: string; due_date: string }[]).map(d => ({ title: d.title, date: d.due_date })),
    outstandingInvoiceCount: invoiceRows.length,
    outstandingInvoiceTotal,
    todayMealsPlanned: todayMeals.count ?? 0,
  }
}

function buildHighlights(s: RawSignals): BriefingHighlight[] {
  const h: BriefingHighlight[] = []
  if (s.todayTasks + s.overdueTasks > 0) h.push({ label: 'Tasks today', value: `${s.todayTasks} due${s.overdueTasks ? ` · ${s.overdueTasks} overdue` : ''}`, link: '/planner', emoji: '📋' })
  if (s.todayHabits > 0) h.push({ label: 'Habits', value: `${s.doneHabits}/${s.todayHabits} done`, link: '/habits', emoji: '🌱' })
  if (s.recentMood != null) h.push({ label: 'Recent mood', value: ['Rough','Low','Okay','Good','Great'][s.recentMood - 1] ?? '?', link: '/mind', emoji: ['😔','😐','🙂','😊','🤩'][s.recentMood - 1] })
  if (s.unreadNotifications > 0) h.push({ label: 'Notifications', value: `${s.unreadNotifications} unread`, link: '/notifications', emoji: '🔔' })
  if (s.birthdaysThisWeek.length > 0) h.push({ label: 'Birthdays this week', value: s.birthdaysThisWeek.map(b => b.name).slice(0, 2).join(', '), link: '/network', emoji: '🎂' })
  if (s.upcomingSIPs.length > 0) h.push({ label: 'SIPs upcoming', value: `${s.upcomingSIPs.length} this week`, link: '/investments', emoji: '💰' })
  if (s.upcomingMaintenance.length > 0) h.push({ label: 'Home tasks', value: `${s.upcomingMaintenance.length} due soon`, link: '/home', emoji: '🛠️' })
  if (s.unpaidBills > 0) h.push({ label: 'Unpaid bills', value: String(s.unpaidBills), link: '/home', emoji: '💡' })
  if (s.activeTrip) h.push({ label: 'Active trip', value: s.activeTrip, link: '/travel', emoji: '✈️' })
  if (s.urgentAuraAlerts > 0) h.push({ label: 'AURA alerts', value: `${s.urgentAuraAlerts} urgent`, link: '/aura', emoji: '👶' })
  if (s.topActiveGoal) h.push({ label: 'Top goal', value: s.topActiveGoal, link: '/career', emoji: '🎯' })
  if (s.upcomingLegalDeadlines.length > 0) h.push({ label: 'Legal deadlines', value: `${s.upcomingLegalDeadlines.length} this week`, link: '/legal', emoji: '⚖️' })
  if (s.outstandingInvoiceCount > 0) h.push({ label: 'Outstanding invoices', value: `${s.outstandingInvoiceCount} · ${Math.round(s.outstandingInvoiceTotal).toLocaleString()}`, link: '/business', emoji: '🧾' })
  if (s.todayMealsPlanned > 0) h.push({ label: 'Meals planned', value: `${s.todayMealsPlanned} today`, link: '/nutrition', emoji: '🥗' })
  return h
}

async function generateBriefingMarkdown(s: RawSignals, userId: string, userName?: string): Promise<string> {
  if (isMockMode()) {
    return mockBriefing(s, userName)
  }

  // Personalisation: tone / verbosity / proactivity / learned patterns
  let personalisationFragment = ''
  try {
    const ctx = await getPersonalisationContext(userId)
    personalisationFragment = ctx.systemFragment
  } catch { /* fail open — never block briefing on personalisation */ }

  const greeting = greetForHour()
  const lines: string[] = []
  lines.push(`Date: ${new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}`)
  lines.push(`Greeting: ${greeting}`)
  lines.push(`User: ${userName ?? 'Friend'}`)
  lines.push(`Tasks: ${s.todayTasks} today, ${s.overdueTasks} overdue, ${s.doneTasks} completed in last 24h`)
  lines.push(`Habits: ${s.doneHabits}/${s.todayHabits} done so far`)
  if (s.recentMood) lines.push(`Mood last logged: ${s.recentMood}/5${s.recentStress != null ? ` (stress ${s.recentStress}/5)` : ''}`)
  if (s.journalDaysAgo != null) lines.push(`Last journal: ${s.journalDaysAgo} days ago`)
  if (s.birthdaysThisWeek.length) lines.push(`Birthdays this week: ${s.birthdaysThisWeek.map(b => b.name).join(', ')}`)
  if (s.followUpsThisWeek.length) lines.push(`Follow-ups due: ${s.followUpsThisWeek.map(f => f.name).join(', ')}`)
  if (s.upcomingSIPs.length) lines.push(`SIPs due this week: ${s.upcomingSIPs.map(p => `${p.name} (${p.amount})`).join(', ')}`)
  if (s.upcomingMaintenance.length) lines.push(`Home maintenance due: ${s.upcomingMaintenance.map(m => m.title).join(', ')}`)
  if (s.unpaidBills > 0) lines.push(`${s.unpaidBills} unpaid utility bills`)
  if (s.activeTrip) lines.push(`Active trip: ${s.activeTrip}`)
  if (s.urgentAuraAlerts) lines.push(`${s.urgentAuraAlerts} urgent AURA alerts (children)`)
  if (s.topActiveGoal) lines.push(`Top career goal: ${s.topActiveGoal}`)
  if (s.upcomingLegalDeadlines.length) lines.push(`Legal/tax deadlines: ${s.upcomingLegalDeadlines.map(d => d.title).join(', ')}`)
  if (s.outstandingInvoiceCount > 0) lines.push(`Outstanding invoices: ${s.outstandingInvoiceCount} totalling ${Math.round(s.outstandingInvoiceTotal)}`)
  if (s.todayMealsPlanned > 0) lines.push(`Meals planned today: ${s.todayMealsPlanned}`)

  const systemPrompt = `You are a warm, calm, slightly poetic morning briefing assistant inside a personal life OS.
Write a 4-6 sentence briefing in markdown. Open with the greeting. Pick the 2-3 most important signals from the data and weave them into a humane narrative — what to focus on, what to celebrate, what to be gentle about.

Rules:
- Use bold for max one phrase that matters most.
- One emoji max in the whole brief.
- Never list more than 3 things.
- Never mention exact numbers if there are none worth mentioning.
- If data is sparse (no tasks, no mood), encourage starting fresh.
- Tone: like a thoughtful friend, not a productivity coach. No "crushing it" energy.
- End with one short, actionable sentence — the next concrete thing.`

  try {
    const result = await generateText({
      model: getAIModel(),
      system: systemPrompt + (personalisationFragment ? '\n\n' + personalisationFragment : ''),
      prompt: `Today's signals:\n${lines.join('\n')}\n\nWrite the morning briefing now (markdown). Apply the user's preferences from above — tone, length, and proactivity should match.`,
      maxOutputTokens: 350,
      temperature: 0.7,
    })
    return result.text.trim()
  } catch (e) {
    console.warn('[briefing] AI failed, falling back to mock', e)
    return mockBriefing(s, userName)
  }
}

function greetForHour(): string {
  const h = new Date().getHours()
  if (h < 5) return 'Late night'
  if (h < 12) return 'Good morning'
  if (h < 17) return 'Good afternoon'
  if (h < 21) return 'Good evening'
  return 'Good night'
}

function mockBriefing(s: RawSignals, userName?: string): string {
  const name = userName ?? 'friend'
  const greeting = greetForHour()
  const parts: string[] = [`**${greeting}, ${name}.**`]

  // Distinguish a *brand-new* user (truly empty across the board) from a user
  // who happens to have a quiet day. The first deserves a welcome, not a poem.
  const isBrandNewUser =
    s.todayTasks + s.overdueTasks + s.doneTasks === 0 &&
    s.todayHabits === 0 &&
    s.recentMood == null &&
    s.journalDaysAgo == null &&
    s.birthdaysThisWeek.length === 0 &&
    s.unpaidBills === 0 &&
    !s.activeTrip
  if (isBrandNewUser) {
    return `**${greeting}, ${name}.** Welcome to Life OS. Your daily briefing will get smarter as you start using it — try adding a task in **Planner**, logging your mood in **Mind**, or setting a budget in **Money**.`
  }

  if (s.todayTasks + s.overdueTasks === 0 && s.todayHabits === 0) {
    parts.push("Today is a blank canvas — no scheduled commitments. A great chance to think about what would actually move you forward.")
  } else {
    if (s.overdueTasks > 0) parts.push(`${s.overdueTasks} overdue ${s.overdueTasks === 1 ? 'task is' : 'tasks are'} waiting — start with the smallest one.`)
    else if (s.todayTasks > 0) parts.push(`${s.todayTasks} ${s.todayTasks === 1 ? 'task' : 'tasks'} on your plate today. Pick the one you'd be proud to finish first.`)
    if (s.todayHabits > 0) parts.push(`Habits: ${s.doneHabits} of ${s.todayHabits} done so far. ${s.doneHabits === s.todayHabits ? '🌱 Beautiful streak.' : 'Small wins compound.'}`)
  }
  if (s.recentMood && s.recentMood <= 2) parts.push("Mood\'s been low — be gentle, you don\'t have to do everything today.")
  if (s.birthdaysThisWeek.length > 0) parts.push(`${s.birthdaysThisWeek[0].name}'s birthday this week — a quick message goes a long way.`)
  parts.push("Take it one block at a time.")
  return parts.join(' ')
}

// ─── Public API ────────────────────────────────────────────────────────────────

export async function getOrCreateBriefing(userId: string, userName?: string, force = false): Promise<BriefingPayload> {
  const today = new Date().toISOString().slice(0, 10)

  if (!isSupabaseConfigured()) {
    const signals = await gatherSignalsSafe(userId)
    return {
      date: today,
      content_md: mockBriefing(signals, userName),
      highlights: buildHighlights(signals),
      generated_at: new Date().toISOString(),
    }
  }

  const db = getSupabaseAdmin()
  if (!force) {
    const { data: existing } = await db
      .from('daily_briefings').select('*').eq('user_id', userId).eq('date', today).maybeSingle()
    if (existing) return existing as BriefingPayload
  }

  const signals = await gatherSignalsSafe(userId)
  const highlights = buildHighlights(signals)
  const content_md = await generateBriefingMarkdown(signals, userId, userName)
  const generated_at = new Date().toISOString()

  await db.from('daily_briefings').upsert({
    user_id: userId, date: today, content_md, highlights, generated_at,
  }, { onConflict: 'user_id,date' })

  return { date: today, content_md, highlights, generated_at }
}

async function gatherSignalsSafe(userId: string): Promise<RawSignals> {
  try { return await gatherSignals(userId) } catch {
    return {
      todayTasks: 0, overdueTasks: 0, doneTasks: 0,
      todayHabits: 0, doneHabits: 0, recentMood: null, recentStress: null,
      unreadNotifications: 0, urgentAuraAlerts: 0,
      birthdaysThisWeek: [], followUpsThisWeek: [],
      upcomingSIPs: [], upcomingMaintenance: [],
      unpaidBills: 0, activeTrip: null, journalDaysAgo: null, topActiveGoal: null,
      upcomingLegalDeadlines: [], outstandingInvoiceCount: 0, outstandingInvoiceTotal: 0,
      todayMealsPlanned: 0,
    }
  }
}
