import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — Life OS',
  description: 'Terms and conditions governing your use of the Life OS platform.',
}

const EFFECTIVE_DATE = '1 May 2026'
const CONTACT_EMAIL = 'legal@lifeos.app'

export default function TermsPage() {
  return (
    <article className="prose prose-gray max-w-none">
      <h1>Terms of Service</h1>
      <p className="lead text-gray-500">Effective date: {EFFECTIVE_DATE}</p>

      <p>Please read these Terms carefully before using Life OS. By creating an account or using the service you agree to be bound by these Terms.</p>

      <h2>1. The service</h2>
      <p>Life OS provides an AI-powered personal assistant accessible at lifeos.app and through our mobile applications. The service includes AI chat, planning tools, focus tools, financial helpers, and family management features.</p>

      <h2>2. Eligibility</h2>
      <p>You must be at least 13 years old to use Life OS. If you are under 18, you confirm that a parent or guardian has agreed to these Terms on your behalf.</p>

      <h2>3. Your account</h2>
      <ul>
        <li>You are responsible for keeping your password confidential.</li>
        <li>You are responsible for all activity that occurs under your account.</li>
        <li>Notify us immediately at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> if you suspect unauthorised access.</li>
        <li>You may not share your account with others or create multiple accounts to circumvent limits.</li>
      </ul>

      <h2>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use Life OS for any unlawful purpose or in violation of any applicable laws</li>
        <li>Attempt to extract, reverse-engineer, or misuse our AI systems</li>
        <li>Submit content that is harmful, abusive, obscene, or infringes third-party rights</li>
        <li>Attempt to gain unauthorised access to any part of the service</li>
        <li>Use automated tools to scrape, crawl, or stress-test the service</li>
        <li>Resell or sublicense access to the service without written permission</li>
      </ul>

      <h2>5. AI-generated content</h2>
      <p>Responses generated by the AI assistant are for informational purposes only. Life OS does not provide legal, medical, financial, or professional advice. Always verify important information with qualified professionals. We are not liable for decisions made based on AI-generated content.</p>

      <h2>6. Subscriptions and billing</h2>
      <ul>
        <li>Free tier: limited AI messages per month.</li>
        <li>Paid plans: billed monthly or annually via Razorpay. Prices are shown at checkout in Indian Rupees (INR).</li>
        <li>Subscriptions renew automatically until cancelled.</li>
        <li>Cancellations take effect at the end of the current billing period — no partial refunds unless required by law.</li>
        <li>We reserve the right to change prices with 30 days&rsquo; notice.</li>
      </ul>

      <h2>7. Intellectual property</h2>
      <p>Life OS and its content are owned by us or our licensors. We grant you a limited, non-exclusive, non-transferable licence to use the service for personal, non-commercial purposes. Your content remains yours; you grant us a licence to process it to provide the service.</p>

      <h2>8. Availability</h2>
      <p>We aim for high availability but do not guarantee uninterrupted access. We may modify, suspend, or discontinue features with reasonable notice. Scheduled maintenance will be communicated in advance where possible.</p>

      <h2>9. Termination</h2>
      <p>You may delete your account at any time in Settings → Account. We may suspend or terminate accounts that violate these Terms, with notice where feasible. Upon termination, your data will be deleted per our Privacy Policy.</p>

      <h2>10. Limitation of liability</h2>
      <p>To the maximum extent permitted by law, Life OS is provided &ldquo;as is&rdquo; without warranties. Our total liability for any claim shall not exceed the amount you paid in the 12 months preceding the claim, or ₹1,000, whichever is greater.</p>

      <h2>11. Governing law</h2>
      <p>These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of Zurich, Switzerland (for international users) or the competent courts of India.</p>

      <h2>12. Changes</h2>
      <p>We may update these Terms. Material changes will be notified 14 days in advance. Continued use after the effective date constitutes acceptance.</p>

      <h2>13. Contact</h2>
      <p>Email: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a></p>
    </article>
  )
}
