export interface Persona {
  id: string
  name: string
  email: string
  password: string
  locale: string
  currency: string
  timezone: string
  country: string
  occupation: string
  personality: string
  dietary: string[]
  modules: string[]  // priority modules
  hasChild: boolean
  childName?: string
  childAge?: number
  hasBusiness: boolean
  accessibilityNeeds: string[]
  rtl: boolean
  notes: string
}

export const PERSONAS: Persona[] = [
  // ─── Batch 1 — Original 10 ──────────────────────────────────────────────────
  {
    id: 'priya',
    name: 'Priya Sharma',
    email: 'priya.sharma@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-IN',
    currency: 'INR',
    timezone: 'Asia/Kolkata',
    country: 'India',
    occupation: 'Software Engineer',
    personality: 'The Coach',
    dietary: ['vegetarian', 'lactose-intolerant'],
    modules: ['Money', 'Investments', 'Career', 'Habits', 'Mind'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '29yo, Bangalore, fintech engineer, single, heavy Money/Career user',
  },
  {
    id: 'james',
    name: 'James Mitchell',
    email: 'james.mitchell@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-GB',
    currency: 'GBP',
    timezone: 'Europe/London',
    country: 'United Kingdom',
    occupation: 'Lawyer',
    personality: 'The Anchor',
    dietary: [],
    modules: ['Legal', 'Family', 'Vault', 'Briefing', 'Travel'],
    hasChild: true,
    childName: 'Oliver',
    childAge: 8,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '45yo, London, lawyer, married with 2 kids',
  },
  {
    id: 'fatima',
    name: 'Fatima Al-Rashid',
    email: 'fatima.alrashid@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'ar-AE',
    currency: 'AED',
    timezone: 'Asia/Dubai',
    country: 'United Arab Emirates',
    occupation: 'Healthcare Consultant',
    personality: 'The Mentor',
    dietary: ['halal'],
    modules: ['Career', 'Network', 'Money', 'Mind', 'Travel'],
    hasChild: true,
    childName: 'Yaseen',
    childAge: 16,
    hasBusiness: false,
    accessibilityNeeds: ['reduced-motion'],
    rtl: true,
    notes: '38yo, Dubai, healthcare consultant, divorced, RTL locale',
  },
  {
    id: 'carlos',
    name: 'Carlos Rodriguez',
    email: 'carlos.rodriguez@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'es-MX',
    currency: 'MXN',
    timezone: 'America/Mexico_City',
    country: 'Mexico',
    occupation: 'Restaurant Owner',
    personality: 'The Sibling',
    dietary: [],
    modules: ['Business', 'Network', 'Nutrition', 'Money', 'Legal'],
    hasChild: false,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '58yo, Mexico City, restaurant owner, married',
  },
  {
    id: 'yuki',
    name: 'Yuki Tanaka',
    email: 'yuki.tanaka@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'ja-JP',
    currency: 'JPY',
    timezone: 'Asia/Tokyo',
    country: 'Japan',
    occupation: 'UX Designer',
    personality: 'The Quiet Friend',
    dietary: ['pescatarian'],
    modules: ['Focus', 'Habits', 'Mind', 'Career', 'Capture'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '26yo, Tokyo, UX designer, single, tiny apartment',
  },
  {
    id: 'sarah',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-US',
    currency: 'USD',
    timezone: 'America/Los_Angeles',
    country: 'United States',
    occupation: 'Product Manager',
    personality: 'The Cheerleader',
    dietary: ['gluten-free', 'vegan'],
    modules: ['Planner', 'Briefing', 'Money', 'Nutrition', 'Career', 'Investments'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '35yo, San Francisco, product manager, married, planning to adopt',
  },
  {
    id: 'abdullah',
    name: 'Abdullah Khan',
    email: 'abdullah.khan@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'ur-PK',
    currency: 'PKR',
    timezone: 'Asia/Karachi',
    country: 'Pakistan',
    occupation: 'Business Owner (Textile Export)',
    personality: 'The Anchor',
    dietary: ['halal'],
    modules: ['Business', 'Family', 'Money', 'Vault', 'Legal', 'AURA'],
    hasChild: true,
    childName: 'Zara',
    childAge: 4,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: true,
    notes: '42yo, Karachi, textile exporter, married, 4 kids, Ramadan-aware',
  },
  {
    id: 'emma',
    name: 'Emma Wilson',
    email: 'emma.wilson@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-AU',
    currency: 'AUD',
    timezone: 'Australia/Sydney',
    country: 'Australia',
    occupation: 'University Student / Barista',
    personality: 'The Quiet Friend',
    dietary: [],
    modules: ['Habits', 'Mind', 'Career', 'Money', 'Community'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '22yo, Sydney, student/barista, eating disorder recovery — recovery-appropriate calorie values',
  },
  {
    id: 'rajesh',
    name: 'Rajesh Patel',
    email: 'rajesh.patel@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'gu-IN',
    currency: 'INR',
    timezone: 'Asia/Kolkata',
    country: 'India',
    occupation: 'Retired Bank Manager',
    personality: 'The Mentor',
    dietary: ['diabetic-friendly'],
    modules: ['Mind', 'Vault', 'Network', 'Home'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: ['large-text', 'high-contrast', 'voice-input'],
    rtl: false,
    notes: '71yo, Ahmedabad, retired, widower, diabetic, Gujarati locale',
  },
  {
    id: 'nina',
    name: 'Nina Okonkwo',
    email: 'nina.okonkwo@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-NG',
    currency: 'NGN',
    timezone: 'Africa/Lagos',
    country: 'Nigeria',
    occupation: 'Freelance Journalist',
    personality: 'The Coach',
    dietary: [],
    modules: ['Money', 'AURA', 'Family', 'Capture', 'Briefing', 'Career'],
    hasChild: true,
    childName: 'Adaeze',
    childAge: 6,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '31yo, Lagos, freelance journalist, single mother',
  },

  // ─── Batch 2 — New personas 11-41 ───────────────────────────────────────────
  {
    id: 'amara',
    name: 'Amara Diallo',
    email: 'amara.diallo@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'fr-SN',
    currency: 'XOF',
    timezone: 'Africa/Dakar',
    country: 'Senegal',
    occupation: 'NGO Director',
    personality: 'The Coach',
    dietary: ['halal'],
    modules: ['Career', 'Network', 'Community', 'Briefing', 'Money'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '34yo, Dakar, NGO director (education), single, Wolof & French speaker',
  },
  {
    id: 'hiroshi',
    name: 'Hiroshi Nakamura',
    email: 'hiroshi.nakamura@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'ja-JP',
    currency: 'JPY',
    timezone: 'Asia/Tokyo',
    country: 'Japan',
    occupation: 'Corporate Executive (VP Operations)',
    personality: 'The Anchor',
    dietary: [],
    modules: ['Investments', 'Money', 'Focus', 'Legal', 'Travel'],
    hasChild: true,
    childName: 'Kenji',
    childAge: 17,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '52yo, Tokyo, VP at electronics conglomerate, married, high earner, investment portfolio',
  },
  {
    id: 'sofia',
    name: 'Sofia Andersen',
    email: 'sofia.andersen@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'da-DK',
    currency: 'DKK',
    timezone: 'Europe/Copenhagen',
    country: 'Denmark',
    occupation: 'Environmental Scientist',
    personality: 'The Quiet Friend',
    dietary: ['vegan'],
    modules: ['Habits', 'Mind', 'Career', 'Nutrition', 'Investments'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '27yo, Copenhagen, environmental researcher, single, cycle commuter, ethical investing',
  },
  {
    id: 'mohamed',
    name: 'Mohamed Hassan',
    email: 'mohamed.hassan@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'ar-EG',
    currency: 'EGP',
    timezone: 'Africa/Cairo',
    country: 'Egypt',
    occupation: 'Civil Engineer',
    personality: 'The Anchor',
    dietary: ['halal'],
    modules: ['Money', 'Home', 'Family', 'Career', 'Legal'],
    hasChild: true,
    childName: 'Youssef',
    childAge: 7,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: true,
    notes: '44yo, Cairo, civil engineer, married+3 kids, RTL Arabic, mortgage+car loan',
  },
  {
    id: 'grace',
    name: 'Grace Kim',
    email: 'grace.kim@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'ko-KR',
    currency: 'KRW',
    timezone: 'Asia/Seoul',
    country: 'South Korea',
    occupation: 'Beauty Startup CEO',
    personality: 'The Cheerleader',
    dietary: [],
    modules: ['Business', 'Career', 'Network', 'Investments', 'Community'],
    hasChild: false,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '30yo, Seoul, K-beauty DTC brand founder (Series A), single, high-growth mindset',
  },
  {
    id: 'dmitri',
    name: 'Dmitri Volkov',
    email: 'dmitri.volkov@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-AE',
    currency: 'AED',
    timezone: 'Asia/Dubai',
    country: 'United Arab Emirates',
    occupation: 'Tech Entrepreneur',
    personality: 'The Mentor',
    dietary: [],
    modules: ['Investments', 'Business', 'Money', 'Protection', 'Travel'],
    hasChild: false,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '38yo, Dubai (Russian origin), SaaS startup founder, married, crypto holdings, investor',
  },
  {
    id: 'isabel',
    name: 'Isabel Ferreira',
    email: 'isabel.ferreira@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'pt-BR',
    currency: 'BRL',
    timezone: 'America/Sao_Paulo',
    country: 'Brazil',
    occupation: 'Social Media Content Creator',
    personality: 'The Cheerleader',
    dietary: [],
    modules: ['Money', 'Career', 'Habits', 'Mind', 'Capture'],
    hasChild: false,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '25yo, São Paulo, Instagram/TikTok creator, irregular income, first apartment, student debt',
  },
  {
    id: 'kofi',
    name: 'Kofi Mensah',
    email: 'kofi.mensah@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-GH',
    currency: 'GHS',
    timezone: 'Africa/Accra',
    country: 'Ghana',
    occupation: 'Secondary School Teacher & Smallholder Farmer',
    personality: 'The Anchor',
    dietary: [],
    modules: ['Money', 'Family', 'Home', 'Community', 'Habits'],
    hasChild: true,
    childName: 'Akosua',
    childAge: 9,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '40yo, Kumasi, teacher + weekend farming, married+4 kids, dual income, mobile-first user',
  },
  {
    id: 'lena',
    name: 'Lena Mueller',
    email: 'lena.mueller@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'de-DE',
    currency: 'EUR',
    timezone: 'Europe/Berlin',
    country: 'Germany',
    occupation: 'Independent Financial Advisor',
    personality: 'The Mentor',
    dietary: [],
    modules: ['Investments', 'Money', 'Business', 'Legal', 'Family'],
    hasChild: true,
    childName: 'Mia',
    childAge: 11,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '47yo, Munich, independent IFA, married+2 kids, pension & investment-savvy, sole trader',
  },
  {
    id: 'arjun',
    name: 'Arjun Nair',
    email: 'arjun.nair@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-SG',
    currency: 'SGD',
    timezone: 'Asia/Singapore',
    country: 'Singapore',
    occupation: 'Fintech Startup Founder',
    personality: 'The Cheerleader',
    dietary: ['vegetarian'],
    modules: ['Business', 'Investments', 'Career', 'Network', 'Focus'],
    hasChild: false,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '33yo, Singapore (Kerala origin), Series A fintech, single, intense work ethic',
  },
  {
    id: 'mei',
    name: 'Mei Chen',
    email: 'mei.chen@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'zh-CN',
    currency: 'GBP',
    timezone: 'Europe/London',
    country: 'United Kingdom',
    occupation: 'PhD Researcher (Computational Biology)',
    personality: 'The Quiet Friend',
    dietary: [],
    modules: ['Money', 'Habits', 'Focus', 'Career', 'Mind'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '29yo, Edinburgh, Chinese PhD student, stipend income, frugal, homesick, travel back to China annually',
  },
  {
    id: 'omar_m',
    name: 'Omar Al-Mansouri',
    email: 'omar.almansouri@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'fr-MA',
    currency: 'MAD',
    timezone: 'Africa/Casablanca',
    country: 'Morocco',
    occupation: 'Hotel & Tourism Business Owner',
    personality: 'The Sibling',
    dietary: ['halal'],
    modules: ['Business', 'Network', 'Money', 'Travel', 'Legal'],
    hasChild: true,
    childName: 'Imane',
    childAge: 14,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '56yo, Marrakech, boutique riad + tourism agency owner, married, seasonal revenue, French speaker',
  },
  {
    id: 'maria',
    name: 'Maria Santos',
    email: 'maria.santos@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-PH',
    currency: 'SAR',
    timezone: 'Asia/Riyadh',
    country: 'Saudi Arabia',
    occupation: 'Registered Nurse (OFW)',
    personality: 'The Cheerleader',
    dietary: ['catholic-fasting'],
    modules: ['Money', 'Family', 'Mind', 'Vault', 'Network'],
    hasChild: true,
    childName: 'Gio',
    childAge: 8,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '36yo, Jeddah (OFW from Manila), nurse, sends SAR remittances to Philippines, separated from family',
  },
  {
    id: 'robert',
    name: 'Robert Williams',
    email: 'robert.williams@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-US',
    currency: 'USD',
    timezone: 'America/New_York',
    country: 'United States',
    occupation: 'Retired US Army Lieutenant Colonel',
    personality: 'The Anchor',
    dietary: [],
    modules: ['Mind', 'Home', 'Vault', 'Investments', 'Legal'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: ['large-text'],
    rtl: false,
    notes: '65yo, Virginia Beach, retired military, widower, pension + VA benefits, PTSD-aware, no jargon preferred',
  },
  {
    id: 'kavya',
    name: 'Kavya Reddy',
    email: 'kavya.reddy@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'te-IN',
    currency: 'INR',
    timezone: 'Asia/Kolkata',
    country: 'India',
    occupation: 'Engineering Student (First-Gen College)',
    personality: 'The Quiet Friend',
    dietary: ['vegetarian'],
    modules: ['Career', 'Money', 'Habits', 'Mind', 'Community'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '22yo, Hyderabad, first-gen engineering student on scholarship, Telugu-speaking, tight budget',
  },
  {
    id: 'tunde',
    name: 'Tunde Adeyemi',
    email: 'tunde.adeyemi@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-GB',
    currency: 'GBP',
    timezone: 'Europe/London',
    country: 'United Kingdom',
    occupation: 'Investment Banker',
    personality: 'The Mentor',
    dietary: [],
    modules: ['Investments', 'Money', 'Career', 'Network', 'Family'],
    hasChild: true,
    childName: 'Dami',
    childAge: 5,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '41yo, London (Nigerian heritage), VP at Barclays, married+2 kids, high earner, Nigeria remittances',
  },
  {
    id: 'leila',
    name: 'Leila Ahmadi',
    email: 'leila.ahmadi@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'de-DE',
    currency: 'EUR',
    timezone: 'Europe/Berlin',
    country: 'Germany',
    occupation: 'Architect',
    personality: 'The Quiet Friend',
    dietary: [],
    modules: ['Career', 'Home', 'Mind', 'Legal', 'Vault'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '32yo, Berlin (Iranian origin), architect at mid-size firm, single immigrant, Farsi+German speaker',
  },
  {
    id: 'patrick',
    name: 'Patrick O\'Brien',
    email: 'patrick.obrien@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-IE',
    currency: 'EUR',
    timezone: 'Europe/Dublin',
    country: 'Ireland',
    occupation: 'Pub Owner (Family Business)',
    personality: 'The Sibling',
    dietary: [],
    modules: ['Business', 'Money', 'Legal', 'Home', 'Network'],
    hasChild: true,
    childName: 'Ciarán',
    childAge: 15,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '55yo, Galway, 3rd-generation pub owner, married+3 kids, post-COVID recovery, seasonal tourism',
  },
  {
    id: 'amelia',
    name: 'Amelia Roberts',
    email: 'amelia.roberts@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-US',
    currency: 'USD',
    timezone: 'America/Denver',
    country: 'United States',
    occupation: 'Middle School Teacher',
    personality: 'The Cheerleader',
    dietary: [],
    modules: ['Money', 'Family', 'Mind', 'Habits', 'Community'],
    hasChild: true,
    childName: 'Ella',
    childAge: 10,
    hasBusiness: false,
    accessibilityNeeds: ['adhd-friendly'],
    rtl: false,
    notes: '42yo, Denver, single mother (2 kids), teacher, ADHD, tight finances, divorce recovery',
  },
  {
    id: 'ravi',
    name: 'Ravi Krishnan',
    email: 'ravi.krishnan@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-LK',
    currency: 'LKR',
    timezone: 'Asia/Colombo',
    country: 'Sri Lanka',
    occupation: 'Senior IT Consultant (Remote)',
    personality: 'The Anchor',
    dietary: [],
    modules: ['Money', 'Investments', 'Career', 'Home', 'Family'],
    hasChild: true,
    childName: 'Dinesh',
    childAge: 12,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '48yo, Colombo, senior IT consultant, USD-remote income, married, LKR savings, economic crisis context',
  },
  {
    id: 'zainab',
    name: 'Zainab Al-Saeedi',
    email: 'zainab.alsaeedi@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'ar-SA',
    currency: 'SAR',
    timezone: 'Asia/Riyadh',
    country: 'Saudi Arabia',
    occupation: 'Fashion Influencer & Brand Consultant',
    personality: 'The Cheerleader',
    dietary: ['halal'],
    modules: ['Business', 'Career', 'Money', 'Investments', 'Vault'],
    hasChild: false,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: true,
    notes: '26yo, Riyadh, fashion creator (800k followers), RTL Arabic, Vision 2030 beneficiary, brand deals',
  },
  {
    id: 'pierre',
    name: 'Pierre Dubois',
    email: 'pierre.dubois@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'fr-FR',
    currency: 'EUR',
    timezone: 'Europe/Paris',
    country: 'France',
    occupation: 'Vineyard Owner & Winemaker',
    personality: 'The Anchor',
    dietary: [],
    modules: ['Business', 'Home', 'Legal', 'Investments', 'Travel'],
    hasChild: false,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '61yo, Bordeaux, 5th-generation vineyard owner, married, estate succession planning, agri-business',
  },
  {
    id: 'aisha',
    name: 'Aisha Mwangi',
    email: 'aisha.mwangi@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'sw-KE',
    currency: 'KES',
    timezone: 'Africa/Nairobi',
    country: 'Kenya',
    occupation: 'FinTech Startup Founder',
    personality: 'The Coach',
    dietary: [],
    modules: ['Business', 'Career', 'Network', 'Money', 'Investments'],
    hasChild: false,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '29yo, Nairobi, mobile-money fintech founder (seed stage), single, M-Pesa-native context',
  },
  {
    id: 'lucas',
    name: 'Lucas Oliveira',
    email: 'lucas.oliveira@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'pt-BR',
    currency: 'BRL',
    timezone: 'America/Sao_Paulo',
    country: 'Brazil',
    occupation: 'Esports Athlete & Streaming Creator',
    personality: 'The Sibling',
    dietary: [],
    modules: ['Money', 'Career', 'Habits', 'Focus', 'Community'],
    hasChild: false,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '37yo, Belo Horizonte, esports pro + Twitch streamer, married, irregular streaming income, night schedule',
  },
  {
    id: 'nadia',
    name: 'Nadia Kovacs',
    email: 'nadia.kovacs@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'hu-HU',
    currency: 'HUF',
    timezone: 'Europe/Budapest',
    country: 'Hungary',
    occupation: 'Psychotherapist (Private Practice)',
    personality: 'The Mentor',
    dietary: [],
    modules: ['Mind', 'Business', 'Career', 'Money', 'Network'],
    hasChild: true,
    childName: 'Bence',
    childAge: 8,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '44yo, Budapest, private psychotherapy practice, divorced+1 son, EU healthcare regulation awareness',
  },
  {
    id: 'rahul',
    name: 'Rahul Mehta',
    email: 'rahul.mehta@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'hi-IN',
    currency: 'INR',
    timezone: 'Asia/Kolkata',
    country: 'India',
    occupation: 'Engineering Student (First Year)',
    personality: 'The Sibling',
    dietary: [],
    modules: ['Money', 'Habits', 'Career', 'Focus', 'Community'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: [],
    rtl: false,
    notes: '19yo, Pune (from Rajasthan), first-year CS student, hostel, pocket money + part-time tutoring',
  },
  {
    id: 'ana',
    name: 'Ana González',
    email: 'ana.gonzalez@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'es-CL',
    currency: 'CLP',
    timezone: 'America/Santiago',
    country: 'Chile',
    occupation: 'Food Blogger & Cookbook Author',
    personality: 'The Cheerleader',
    dietary: [],
    modules: ['Business', 'Nutrition', 'Career', 'Money', 'Travel'],
    hasChild: false,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '50yo, Santiago, food blog (500k followers) + published cookbook, married (adult kids), recipe business',
  },
  {
    id: 'ivan',
    name: 'Ivan Marchenko',
    email: 'ivan.marchenko@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'uk-UA',
    currency: 'PLN',
    timezone: 'Europe/Warsaw',
    country: 'Poland',
    occupation: 'IT Freelancer (Remote)',
    personality: 'The Quiet Friend',
    dietary: [],
    modules: ['Money', 'Career', 'Mind', 'Legal', 'Vault'],
    hasChild: false,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '35yo, Warsaw (from Kyiv, war-displaced), IT freelancer (USD billed), Ukrainian speaker, refugee context',
  },
  {
    id: 'hana_y',
    name: 'Hana Yamamoto',
    email: 'hana.yamamoto@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'ja-JP',
    currency: 'JPY',
    timezone: 'Asia/Tokyo',
    country: 'Japan',
    occupation: 'Retired Primary School Teacher',
    personality: 'The Quiet Friend',
    dietary: [],
    modules: ['Mind', 'Home', 'Vault', 'Network', 'Habits'],
    hasChild: false,
    hasBusiness: false,
    accessibilityNeeds: ['large-text', 'high-contrast'],
    rtl: false,
    notes: '68yo, Osaka, retired teacher, widowed, pension income, elder care planning, tech-novice',
  },
  {
    id: 'michael',
    name: 'Michael Osei',
    email: 'michael.osei@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'en-GH',
    currency: 'GHS',
    timezone: 'Africa/Accra',
    country: 'Ghana',
    occupation: 'Football Coach & Youth Academy Founder',
    personality: 'The Mentor',
    dietary: [],
    modules: ['Career', 'Business', 'Community', 'Money', 'Network'],
    hasChild: false,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '31yo, Accra, youth football academy founder, married, social impact focus, sports nutrition awareness',
  },
  {
    id: 'preethi',
    name: 'Preethi Kumar',
    email: 'preethi.kumar@e2e-test.handlelifeos.app',
    password: 'E2eTest123!',
    locale: 'ta-IN',
    currency: 'INR',
    timezone: 'Asia/Kolkata',
    country: 'India',
    occupation: 'EdTech Startup Founder (ex-homemaker)',
    personality: 'The Coach',
    dietary: ['vegetarian'],
    modules: ['Business', 'Career', 'Family', 'Mind', 'Network'],
    hasChild: true,
    childName: 'Arya',
    childAge: 7,
    hasBusiness: true,
    accessibilityNeeds: [],
    rtl: false,
    notes: '38yo, Chennai, left corporate career to raise kids, now building EdTech platform, married+2 kids, Tamil speaker',
  },
]
